"""Single source for the report tables (Word) and the draw.io ERD.

Mirrors docs/capstone-db-schema.md. Each entity: (name, intro sentence, [(field, type, description)]).
`type` carries the key marker in parentheses, like the report: "bigint (PK)", "bigint (FK)", "varchar(150) (UK)".
Relations: (child_table, child_field, parent_table, parent_field, kind) kind: "n1" many-to-one, "11" one-to-one.
"""

ENTITIES = [
    ("users", "Stores every account of the system: students, lecturers and administrators.", [
        ("user_id", "bigint (PK)", "Unique user identifier"),
        ("email", "citext (UK)", "Login email, case-insensitive and unique"),
        ("password_hash", "text", "bcrypt/argon2 hash of the password, never plaintext"),
        ("full_name", "varchar(150)", "Display name of the user"),
        ("role", "enum", "STUDENT, LECTURER or ADMIN"),
        ("department", "varchar(100)", "Department or faculty of the user"),
        ("is_active", "boolean", "Soft-delete flag"),
        ("created_at", "timestamptz", "Creation time"),
        ("updated_at", "timestamptz", "Last update time"),
    ]),
    ("lecturer_profiles", "Public directory information that only lecturers have.", [
        ("user_id", "bigint (PK, FK)", "Foreign key referencing users(user_id); must be a LECTURER"),
        ("slug", "varchar(80) (UK)", "URL-friendly name, e.g. amara-chen"),
        ("photo_url", "text", "Profile photo address"),
        ("blurb", "varchar(280)", "Short description shown on the directory card"),
        ("specialty", "varchar(100)", "Main teaching or research area"),
    ]),
    ("password_reset_tokens", "Single-use tokens for the forgot-password flow.", [
        ("token_id", "bigint (PK)", "Unique token record identifier"),
        ("user_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("token_hash", "text (UK)", "SHA-256 of the raw token; the raw value only exists in the emailed link"),
        ("expires_at", "timestamptz", "Expiry time (creation + 30 minutes)"),
        ("used_at", "timestamptz", "Set when redeemed; NULL means still usable"),
        ("created_at", "timestamptz", "Creation time"),
    ]),
    ("semesters", "Academic terms that scope availability, timetables and bookings.", [
        ("semester_id", "bigint (PK)", "Unique semester identifier"),
        ("name", "varchar(100)", "Semester name"),
        ("start_date", "date", "First day of the semester"),
        ("end_date", "date", "Last day of the semester (must be after start_date)"),
        ("is_active", "boolean", "Marks the current semester"),
    ]),
    ("availability_rules", "Keeps templates for weekly consultations shown by lecturers.", [
        ("rule_id", "bigint (PK)", "Unique rule identifier"),
        ("lecturer_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("semester_id", "bigint (FK)", "Foreign key referencing semesters(semester_id)"),
        ("day_of_week", "smallint", "Day index (1 = Monday, ..., 7 = Sunday)"),
        ("start_time", "time", "Daily window start time"),
        ("end_time", "time", "Daily window end time"),
        ("slot_minutes", "int", "Length of each generated slot in minutes"),
        ("effective_from", "date", "First date the rule applies"),
        ("effective_to", "date", "Last date the rule applies"),
        ("created_at", "timestamptz", "Creation time"),
    ]),
    ("availability_exceptions", "One-off changes to a lecturer's availability on a specific date.", [
        ("exception_id", "bigint (PK)", "Unique exception identifier"),
        ("lecturer_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("exception_date", "date", "Date the exception applies to"),
        ("type", "enum", "BLOCK removes time, ADD opens extra time"),
        ("start_time", "time", "Exception window start time"),
        ("end_time", "time", "Exception window end time"),
        ("reason", "varchar(255)", "Optional explanation"),
        ("created_at", "timestamptz", "Creation time"),
    ]),
    ("slots", "Concrete bookable time slots generated from availability rules.", [
        ("slot_id", "bigint (PK)", "Unique slot identifier"),
        ("lecturer_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("rule_id", "bigint (FK)", "Foreign key referencing availability_rules(rule_id); NULL for ad-hoc slots"),
        ("start_at", "timestamptz", "Slot start time"),
        ("end_at", "timestamptz", "Slot end time"),
        ("capacity", "int", "Maximum students allowed in the slot"),
        ("status", "enum", "OPEN, FULL or CLOSED"),
    ]),
    ("schedule_entries", "Contains the schedule of busy slots of the students and lecturers.", [
        ("entry_id", "bigint (PK)", "Unique entry identifier"),
        ("user_id", "bigint (FK)", "Foreign key referencing users(user_id); owner of the block"),
        ("semester_id", "bigint (FK)", "Foreign key referencing semesters(semester_id)"),
        ("title", "varchar(200)", "Display title of the block"),
        ("subject_code", "varchar(30)", "Course code, e.g. CS 301"),
        ("subject_name", "varchar(150)", "Course name"),
        ("group_code", "varchar(20)", "Class group / section"),
        ("day_of_week", "smallint", "Day index (1 = Monday, ..., 7 = Sunday)"),
        ("date_label", "varchar(20)", "Calendar date printed in the source timetable"),
        ("start_time", "time", "Block start time"),
        ("end_time", "time", "Block end time"),
        ("room", "varchar(100)", "Room or online link"),
        ("location_type", "enum", "LAB, ROOM, ONLINE or OTHER"),
        ("lecturer_name", "varchar(150)", "Instructor of the class (free text)"),
        ("color_hue", "varchar(20)", "Display colour token"),
        ("notes", "text", "Optional notes"),
        ("source", "varchar(20)", "AAO_IMPORT or MANUAL"),
        ("import_batch_id", "bigint (FK)", "Foreign key referencing schedule_imports(import_id)"),
    ]),
    ("schedule_imports", "Audit trail of every timetable batch uploaded from the browser.", [
        ("import_id", "bigint (PK)", "Unique import identifier"),
        ("semester_id", "bigint (FK)", "Foreign key referencing semesters(semester_id)"),
        ("uploaded_by", "bigint (FK)", "Foreign key referencing users(user_id); who sent the batch"),
        ("target_user_id", "bigint (FK)", "Foreign key referencing users(user_id); NULL for self-service"),
        ("source_files", "text[]", "Original PDF file names (audit only)"),
        ("mode", "enum", "REPLACE or MERGE"),
        ("status", "enum", "QUEUED, PROCESSING, COMPLETED or FAILED"),
        ("rows_processed", "int", "Rows received in the payload"),
        ("rows_added", "int", "Rows inserted into schedule_entries"),
        ("rows_replaced", "int", "Previously imported rows removed by REPLACE"),
        ("rows_failed", "int", "Rows rejected by validation"),
        ("rows_skipped", "int", "Duplicate rows skipped by MERGE"),
        ("error_log", "jsonb", "Per-row error details"),
        ("created_at", "timestamptz", "Upload time"),
        ("completed_at", "timestamptz", "Completion time"),
    ]),
    ("schedule_import_staging", "Deferred (not in the MVP): temporary buffer for server-side bulk ingestion.", [
        ("staging_id", "bigint (PK)", "Unique staging row identifier"),
        ("import_batch_id", "bigint (FK)", "Foreign key referencing schedule_imports(import_id)"),
        ("temp_row_num", "int", "Row number inside the uploaded file"),
        ("user_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("semester_id", "bigint (FK)", "Foreign key referencing semesters(semester_id)"),
        ("title", "varchar(200)", "Display title"),
        ("subject_code", "varchar(30)", "Course code"),
        ("subject_name", "varchar(150)", "Course name"),
        ("group_code", "varchar(20)", "Class group / section"),
        ("day_of_week", "smallint", "Day index (1 = Monday, ..., 7 = Sunday)"),
        ("start_time", "time", "Block start time"),
        ("end_time", "time", "Block end time"),
        ("room", "varchar(100)", "Room or online link"),
        ("location_type", "enum", "LAB, ROOM, ONLINE or OTHER"),
        ("lecturer_name", "varchar(150)", "Instructor of the class"),
        ("status", "enum", "VALID, DUPLICATE, CONFLICT or INVALID"),
        ("conflict_notes", "text", "Explanation for non-valid rows"),
        ("created_at", "timestamptz", "Creation time"),
    ]),
    ("bookings", "Student requests for a lecturer's slot and their lifecycle.", [
        ("booking_id", "bigint (PK)", "Unique booking identifier"),
        ("slot_id", "bigint (FK)", "Foreign key referencing slots(slot_id)"),
        ("student_id", "bigint (FK)", "Foreign key referencing users(user_id); the requester"),
        ("semester_id", "bigint (FK)", "Foreign key referencing semesters(semester_id)"),
        ("status", "enum", "PENDING, CONFIRMED, DECLINED, CANCELLED, COMPLETED or NO_SHOW"),
        ("is_group", "boolean", "True when several students attend"),
        ("topic", "varchar(255)", "What the student wants to discuss"),
        ("time_range", "tstzrange", "Copy of the slot interval, used by the double-booking constraint"),
        ("decline_reason", "varchar(255)", "Reason given by the lecturer when declining"),
        ("created_at", "timestamptz", "Request time"),
        ("confirmed_at", "timestamptz", "Confirmation time"),
        ("cancelled_at", "timestamptz", "Cancellation time"),
        ("cancelled_by", "bigint (FK)", "Foreign key referencing users(user_id)"),
    ]),
    ("booking_participants", "Additional students in a group booking.", [
        ("booking_id", "bigint (PK, FK)", "Foreign key referencing bookings(booking_id)"),
        ("student_id", "bigint (PK, FK)", "Foreign key referencing users(user_id); added by email"),
        ("joined_at", "timestamptz", "Time the student joined"),
    ]),
    ("meeting_records", "Outcome of a finished consultation.", [
        ("record_id", "bigint (PK)", "Unique record identifier"),
        ("booking_id", "bigint (FK, UK)", "Foreign key referencing bookings(booking_id)"),
        ("attended", "boolean", "Whether the student attended"),
        ("notes", "text", "Optional free-text notes"),
        ("recorded_at", "timestamptz", "Time the record was saved"),
    ]),
    ("recurring_bookings", "Weekly repeating consultations between a student and a lecturer.", [
        ("recurring_id", "bigint (PK)", "Unique recurring booking identifier"),
        ("student_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("lecturer_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("semester_id", "bigint (FK)", "Foreign key referencing semesters(semester_id)"),
        ("day_of_week", "smallint", "Day index (1 = Monday, ..., 7 = Sunday)"),
        ("start_time", "time", "Weekly start time"),
        ("end_time", "time", "Weekly end time"),
        ("is_cancelled", "boolean", "True once the series is stopped"),
        ("created_at", "timestamptz", "Creation time"),
    ]),
    ("waitlist_entries", "Queue of students waiting for a full slot.", [
        ("waitlist_id", "bigint (PK)", "Unique waitlist entry identifier"),
        ("slot_id", "bigint (FK)", "Foreign key referencing slots(slot_id)"),
        ("student_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("requested_at", "timestamptz", "Time the student joined the queue"),
        ("priority_score", "numeric(10,4)", "Score computed by the active allocation policy"),
        ("status", "enum", "WAITING, OFFERED, EXPIRED, FULFILLED or CANCELLED"),
        ("offered_at", "timestamptz", "Time the slot was offered"),
        ("offer_expires_at", "timestamptz", "Deadline to accept the offer"),
    ]),
    ("allocation_policies", "Available fairness policies and their parameters.", [
        ("policy_id", "bigint (PK)", "Unique policy identifier"),
        ("name", "varchar(30) (UK)", "FCFS, NEED, ROUND_ROBIN or HYBRID"),
        ("config", "jsonb", "Policy parameters"),
        ("is_active", "boolean", "Marks the policy currently in use"),
    ]),
    ("allocation_events", "Audit log of every allocation decision, reproducible with its seed.", [
        ("event_id", "bigint (PK)", "Unique event identifier"),
        ("waitlist_entry_id", "bigint (FK)", "Foreign key referencing waitlist_entries(waitlist_id)"),
        ("policy_id", "bigint (FK)", "Foreign key referencing allocation_policies(policy_id)"),
        ("computed_score", "numeric(10,4)", "Score of the student at decision time"),
        ("decision", "enum", "SELECTED, SKIPPED or OVERRIDDEN"),
        ("random_seed", "int", "Seed that makes the decision reproducible"),
        ("overridden_by", "bigint (FK)", "Foreign key referencing users(user_id); the admin who overrode"),
        ("created_at", "timestamptz", "Decision time"),
    ]),
    ("synthetic_demand_runs", "Generated demand datasets used for fairness experiments.", [
        ("run_id", "bigint (PK)", "Unique run identifier"),
        ("seed", "int", "Random seed of the generator"),
        ("popularity_skew", "numeric(5,2)", "How unevenly demand concentrates on few lecturers"),
        ("arrival_pattern", "varchar(30)", "Shape of request arrivals"),
        ("num_students", "int", "Number of simulated students"),
        ("num_lecturers", "int", "Number of simulated lecturers"),
        ("generated_at", "timestamptz", "Generation time"),
        ("dataset", "jsonb", "Full generated dataset"),
    ]),
    ("experiments", "Results of running a policy on a demand dataset.", [
        ("experiment_id", "bigint (PK)", "Unique experiment identifier"),
        ("demand_run_id", "bigint (FK)", "Foreign key referencing synthetic_demand_runs(run_id)"),
        ("policy_id", "bigint (FK)", "Foreign key referencing allocation_policies(policy_id)"),
        ("seed", "int", "Seed used for the run"),
        ("gini_slots_per_student", "numeric(6,4)", "Gini index of slots per student"),
        ("gini_lecturer_access", "numeric(6,4)", "Gini index of access across lecturers"),
        ("max_min_ratio", "numeric(10,4)", "Ratio between best-served and worst-served student"),
        ("pct_students_with_slot", "numeric(5,2)", "Share of students who got a slot"),
        ("slot_utilization_pct", "numeric(5,2)", "Share of slots that were filled"),
        ("avg_time_to_fill_seconds", "int", "Average time to fill a slot"),
        ("offer_rejection_rate_pct", "numeric(5,2)", "Share of offers rejected or expired"),
        ("avg_wait_time_seconds", "int", "Average waiting time"),
        ("wait_time_variance", "numeric(14,4)", "Variance of waiting time"),
        ("run_at", "timestamptz", "Run time"),
    ]),
    ("notifications", "In-app notifications delivered to users.", [
        ("notification_id", "bigint (PK)", "Unique notification identifier"),
        ("user_id", "bigint (FK)", "Foreign key referencing users(user_id)"),
        ("type", "varchar(50)", "booking.pending, booking.confirmed, booking.declined, booking.cancelled, waitlist.offered, waitlist.expired or reminder.upcoming"),
        ("payload", "jsonb", "Event data used to render the message"),
        ("read_at", "timestamptz", "Time the user read it; NULL means unread"),
        ("created_at", "timestamptz", "Creation time"),
    ]),
]

# (child, child_field, parent, parent_field, kind)
RELATIONS = [
    ("lecturer_profiles", "user_id", "users", "user_id", "11"),
    ("password_reset_tokens", "user_id", "users", "user_id", "n1"),
    ("notifications", "user_id", "users", "user_id", "n1"),
    ("availability_rules", "lecturer_id", "users", "user_id", "n1"),
    ("availability_rules", "semester_id", "semesters", "semester_id", "n1"),
    ("availability_exceptions", "lecturer_id", "users", "user_id", "n1"),
    ("slots", "lecturer_id", "users", "user_id", "n1"),
    ("slots", "rule_id", "availability_rules", "rule_id", "n1"),
    ("schedule_entries", "user_id", "users", "user_id", "n1"),
    ("schedule_entries", "semester_id", "semesters", "semester_id", "n1"),
    ("schedule_entries", "import_batch_id", "schedule_imports", "import_id", "n1"),
    ("schedule_imports", "uploaded_by", "users", "user_id", "n1"),
    ("schedule_imports", "semester_id", "semesters", "semester_id", "n1"),
    ("schedule_import_staging", "import_batch_id", "schedule_imports", "import_id", "n1"),
    ("bookings", "slot_id", "slots", "slot_id", "n1"),
    ("bookings", "student_id", "users", "user_id", "n1"),
    ("bookings", "semester_id", "semesters", "semester_id", "n1"),
    ("booking_participants", "booking_id", "bookings", "booking_id", "n1"),
    ("booking_participants", "student_id", "users", "user_id", "n1"),
    ("meeting_records", "booking_id", "bookings", "booking_id", "11"),
    ("recurring_bookings", "student_id", "users", "user_id", "n1"),
    ("recurring_bookings", "lecturer_id", "users", "user_id", "n1"),
    ("waitlist_entries", "slot_id", "slots", "slot_id", "n1"),
    ("waitlist_entries", "student_id", "users", "user_id", "n1"),
    ("allocation_events", "waitlist_entry_id", "waitlist_entries", "waitlist_id", "n1"),
    ("allocation_events", "policy_id", "allocation_policies", "policy_id", "n1"),
    ("experiments", "demand_run_id", "synthetic_demand_runs", "run_id", "n1"),
    ("experiments", "policy_id", "allocation_policies", "policy_id", "n1"),
]

# Grid layout for the draw.io diagram: one list per column, top to bottom.
LAYOUT = [
    ["users", "lecturer_profiles", "password_reset_tokens", "notifications"],
    ["semesters", "availability_rules", "availability_exceptions", "slots"],
    ["bookings", "booking_participants", "meeting_records", "recurring_bookings"],
    ["waitlist_entries", "allocation_events", "allocation_policies", "experiments", "synthetic_demand_runs"],
    ["schedule_entries", "schedule_imports", "schedule_import_staging"],
]
